# EKS Cluster Outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = aws_eks_cluster.ambience_cluster.id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = aws_eks_cluster.ambience_cluster.arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.ambience_cluster.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_eks_cluster.ambience_cluster.vpc_config[0].cluster_security_group_id
}

output "cluster_version" {
  description = "EKS cluster version"
  value       = aws_eks_cluster.ambience_cluster.version
}

output "cluster_platform_version" {
  description = "Platform version for the EKS cluster"
  value       = aws_eks_cluster.ambience_cluster.platform_version
}

output "cluster_status" {
  description = "Status of the EKS cluster"
  value       = aws_eks_cluster.ambience_cluster.status
}

# Kubeconfig
output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/kubeconfig_template.yaml", {
    cluster_name     = aws_eks_cluster.ambience_cluster.name
    cluster_endpoint = aws_eks_cluster.ambience_cluster.endpoint
    cluster_ca       = aws_eks_cluster.ambience_cluster.certificate_authority[0].data
    aws_region       = var.aws_region
  })
  sensitive = true
}

# Node Group Outputs
output "node_group_arn" {
  description = "Amazon Resource Name (ARN) of the EKS Node Group"
  value       = aws_eks_node_group.ambience_node_group.arn
}

output "node_group_status" {
  description = "Status of the EKS Node Group"
  value       = aws_eks_node_group.ambience_node_group.status
}

# VPC Outputs
output "vpc_id" {
  description = "ID of the VPC where the cluster security group belongs"
  value       = aws_vpc.ambience_vpc.id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = aws_vpc.ambience_vpc.cidr_block
}

output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private_subnets[*].id
}

output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = aws_subnet.public_subnets[*].id
}

# IAM Role ARNs
output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster"
  value       = aws_iam_role.eks_cluster_role.arn
}

output "node_group_iam_role_arn" {
  description = "IAM role ARN of the EKS node group"
  value       = aws_iam_role.eks_node_group_role.arn
}

# Instructions for connecting to the cluster
output "cluster_connection_instructions" {
  description = "Instructions for connecting to the EKS cluster"
  value       = <<-EOT
    To connect to your EKS cluster:
    
    1. Install kubectl and AWS CLI if not already installed
    2. Configure AWS credentials with appropriate permissions
    3. Update your kubeconfig:
       aws eks update-kubeconfig --region ${var.aws_region} --name "${var.cluster_name}"
    4. Verify connection:
       kubectl get nodes
    
    Cluster Endpoint: ${aws_eks_cluster.ambience_cluster.endpoint}
    Cluster Name: ${var.cluster_name}
    Region: ${var.aws_region}
  EOT
}